ext-mappings:
  img:
    raw: 
    - cr2
    - cr3
    - dng
    prc:
    - jpg
    - png
  vid:
    raw: 
    - mp4
    - mov
gdrive-mime-type-mappings:
  application/octet-stream: 
  - cr2
  - cr3
  image/dng:
  - dng
  image/jepg:
  - jpg
  image/png:
  - png
  video/mp4: 
  - mp4
  video/quicktime:
  - mov
  application/xml:
  - xmp
  text/plain:
  - arp
  - pp3
remote-repo-roots:
  - name: kalutara
    url: pix@kalutara.local:photos
    push-rating: 0
    pull-rating: 0
  - name: gdrive
    url: gdrive:pixync
    push-rating: 5
    pull-rating: 0
  - name: samsung_t5_ssd
    url: /media/chamith/T5_500GB/Pictures